/**
 * GENERATED by scripts/gen-versions.mjs — do not edit by hand.
 *
 * Sources: the pnpm catalog (pnpm-workspace.yaml), packages/cli/package.json,
 * and scripts/lib/template-versions.json. Regenerate with `pnpm gen:versions`;
 * `pnpm verify:catalog` fails when this file is stale.
 */

/** The core line: every package published from signalxjs/core shares it. */
export const SIGX_CORE = '^1.0.0';

/** `@sigx/cli`'s own single-minor range, for templates whose scripts run `sigx`. */
export const SIGX_CLI = '^0.14.0';

/** Packages on the core line (mirrors scripts/lib/core-deps.mjs). */
export const SIGX_CORE_PACKAGES: ReadonlySet<string> = new Set([
    'sigx',
    '@sigx/serialize',
    '@sigx/reactivity',
    '@sigx/runtime-core',
    '@sigx/runtime-dom',
    '@sigx/server-renderer',
    '@sigx/ssr-islands',
    '@sigx/resume',
    '@sigx/cache',
    '@sigx/server',
    '@sigx/vite',
    '@sigx/cloudflare',
    '@sigx/vercel',
    '@sigx/netlify',
]);

/** Companion packages with their own release lines. */
export const SIGX_COMPANIONS: Readonly<Record<string, string>> = {
    '@sigx/router': '^0.13.0',
    '@sigx/i18n': '^0.4.0',
    '@sigx/store': '^0.14.0',
    '@sigx/ssg': '^0.22.0',
    '@sigx/ssg-theme-daisyui': '^0.22.0',
    '@sigx/daisyui': '^0.13.0',
    '@sigx/terminal': '^0.13.0',
    '@sigx/terminal-dev': '^0.13.0',
    '@sigx/actors': '^0.11.0',
    '@sigx/actors-cloudflare': '^0.11.0',
    '@sigx/lynx': '^0.34.0',
};

/** Third-party pins. */
export const THIRD_PARTY: Readonly<Record<string, string>> = {
    'vite': '^8.3.1',
    'typescript': '^7.0.2',
    'typescript-lynx': '^6.0.3',
    '@types/node': '^24.0.0',
    'express': '^5.2.1',
    '@types/express': '^5.0.6',
    'cross-env': '^10.1.0',
    'tailwindcss': '^4.3.0',
    '@tailwindcss/vite': '^4.3.0',
    'daisyui': '^5.7.0',
    'tsx': '^4.23.0',
    'vitest': '^5.0.2',
    'oxlint': '^1.85.0',
    'wrangler': '^4.141.0',
    '@types/bun': '^1.4.0',
    '@cloudflare/workers-types': '^5.20260927.0',
    'happy-dom': '^20.14.0',
    '@lynx-js/rspeedy': '^0.16.3',
    '@lynx-js/css-extract-webpack-plugin': '^0.10.1',
    '@lynx-js/template-webpack-plugin': '0.15.0',
    '@lynx-js/runtime-wrapper-webpack-plugin': '^0.2.3',
    '@lynx-js/webpack-dev-transport': '^0.3.0',
    '@lynx-js/tailwind-preset': '^0.5.0',
};
